@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    interface "<size:14>Matcher\n<size:10>BuildingCentreReceipt" as BuildingCentreReceipt.Matcher<T> [[Matcher.html]] {
        {abstract} +matches(T): boolean
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
